version: '3.1'
services:

  web:
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    volumes:
      - ./:/var/www

  #MySQL Service
  db:
    image: mariadb
    container_name : guru_db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: trianggautama08
      MYSQL_DATABASE: guru_db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_HOST=db
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions
      links:
          - db
